import { Translations } from './translations.type';

export const EN: Translations = {
    /* ── Nav ── */
    nav: [
        { label: 'THE NAME', link: '#accordion' },
        { label: 'PAPERS', link: '#papers' },
        { label: 'KPIS', link: '#kpis' },
        { label: 'ABOUT US', link: '#horizontal-collapsible' },
        { label: 'AWARDS', link: '#awards' },
        {
            label: 'THE GROUP', children: [
                { label: 'SciTheWorld', link: 'https://scitheworld.com' },
                { label: 'Algorithmization', link: 'https://algorithmization.com' },
                { label: 'SystematicMe', link: 'https://systematicme.com' },
                { label: '41OPS', link: 'https://41ops.com' }
            ]
        },
        { label: 'CONTACT', link: '#contact' }
    ],

    /* ── Hero ── */
    hero: {
        title: 'Proprietary investment opportunities',
        subtitle: 'LEARNING~ADAPTIVE',
    },

    /* ── Part STW ── */
    partStw: {
        titleHtml: 'Part of <u>SciTheWorld</u>',
        description: `<p>We are an investment spin-off from SciTheWorld:</p>
<ol>
  <li>SciTheWorld was built to create applied science, proprietary technology, and extreme efficiency. Learning~Adaptive exists to professionally invest the capital generated by that effort, following the same discipline that governed its creation.</li>
  <li>It is a venture tech investment of the Group: first operating as a family office, and—once fully proven by its own capital—progressively opening to third-party mandates.</li>
</ol>`,
    },

    /* ── Accordion ── */
    accordion: {
        sectionTitle: 'THE NAME',
        sectionSubtitle: `The name Learning~Adaptive is not symbolic. It is literal.\n`,
        cards: [
            {
                title: 'AN EARLY CAREER',
                description: `It refers to Sergio Álvarez-Teleña's pioneering work on algorithmic trading, first formalized in 2012 as a book "Trading 2.0: Learning~Adaptive Machines" —a body of work that later became the foundation of his PhD thesis at University College London (Computer Science).\n\nThe thesis was supervised within an environment closely connected to the most demanding standards of quantitative finance, including leadership linked to Renaissance Technologies—a firm long admired for its rigor and results.`,
            },
            {
                title: 'A PRIVILEGED TECH',
                description: `The name reflects continuity of thought and a cold, disciplined commitment to reaching the highest standards—pursued relentlessly since 2012 and achieving all sorts of recognitions and awards ever since.`,
            }
        ],
    },

    /* ── KPIs ── */
    kpis: {
        title: 'KPIs',
        subtitle: 'A LONG RUN PROJECT',
        items: [
            { value: '200%+', description: 'P&L at Santander\u2019s Structured Notes within two years.' },
            { value: '400%+', description: 'P&L at Morgan Stanley\u2019s Custom Indices within a year.' },
            { value: '38% & 84%', description: 'returns while bootstrapping SciTheWorld during COVID.' },
            { value: '€1Billion+', description: 'invested by a tier one bank upon our technology.' }
        ],
    },

    /* ── Papers ── */
    papers: {
        title: 'White Papers',
        subtitle: 'A LONG RUN PROJECT',
    },

    /* ── Horizontal Sections Structure ── */
    horizontalSectionsStructure: [
        { title: 'A unique investment infrastructure', subtitle: '' },
        { title: 'A unique investment infrastructure', subtitle: '' },
        { title: 'In one sentence', subtitle: '' },
    ],

    /* ── Section quote (collapsible-3) ── */
    sectionQuote: '[ Learning~Adaptive is an investment vehicle built on applied science and AI-native infrastructure, designed to deliver long-term capital compounding through structural efficiency and a continuous creation of optionality upon SciTheWorld Group. ]',

    /* ── Collapsible Lists ── */
    collapsibleList1: [
        {
            title: '1. Public markets — Alpha Dynamics',
            content: `For liquid markets, Learning~Adaptive leverages Alpha Dynamics, SciTheWorld's AI-native investment platform. Alpha Dynamics spans:
<ul>
  <li>algorithmic portfolio construction,</li>
  <li>algorithmic execution,</li>
  <li>algorithmic market making,</li>
  <li>and algorithmic risk management,</li>
</ul>
as formalized in SciTheWorld's trilogy of papers on modern investment management.
This is not tooling layered on top of legacy processes; it is investment infrastructure designed from algorithmic first principles.`,
        },
        {
            title: '2. Private markets — Fractal',
            content: `In private markets, Learning~Adaptive goes beyond capital allocation.
By leveraging Fractal, SciTheWorld's End-to-End, AI-first corporate technology, it can:
<ul>
  <li>actively turbo-boost portfolio companies,</li>
  <li>accelerate their AI-native transformation,</li>
  <li>and unlock synergies across investments within the portfolio.</li>
</ul>
Private investments are not treated as isolated positions, but as interacting components of a system.`,
        },
        {
            title: '3. Extreme-efficiency as a structural advantage',
            content: `Learning~Adaptive inherits SciTheWorld's culture of extreme efficiency:
<ul>
  <li>minimal human overhead,</li>
  <li>AI-native operations,</li>
  <li>architecture-first design.</li>
</ul>
This allows the vehicle to:
<ul>
  <li>reinvest continuously in innovation,</li>
  <li>protect fund margins,</li>
  <li>and avoid fee inflation driven by operational bloat.</li>
</ul>
Efficiency is not a cost tactic; it is a compounding investment advantage.`,
        },
        {
            title: '4. Federated architecture and IP protection',
            content: `The Group's federated architecture protects intellectual property from individual dependency and staff rotation—mitigating the classic "star risk" of investment teams.
Knowledge is institutionalized, not person-bound.
This enables long-term continuity without sacrificing innovation.`,
        },
        {
            title: '5. Collaboration-native by design',
            content: `One of the consequences from being built upon federated technology is that Learning~Adaptive is structurally open to collaboration:
<ul>
  <li>with universities,</li>
  <li>asset managers,</li>
  <li>sector associations,</li>
  <li>and specialized partners.</li>
</ul>
Revenue sharing and co-development are not exceptions; they are native features of the architecture.`,
        },
        {
            title: '6. Global, forward-looking intelligence',
            content: `Through SciTheWorld, Learning~Adaptive continuously absorbs privileged signal on:
<ul>
  <li>where innovation is truly advancing,</li>
  <li>which sectors are structurally lagging,</li>
  <li>and where systemic risk is accumulating.</li>
</ul>
This perspective spans companies, sectors, and nations—not just markets.`,
        },
    ],

    collapsibleList2: [
        {
            title: '7. Augmented Machines in investment',
            content: `Learning~Adaptive applies Augmented Machines technology:
a disciplined combination of machine-generated signals and human judgment.
Machines optimize scale and precision.
Humans arbitrate context, regime change, and risk.
This is not discretionary vs. systematic—it is structured cooperation.`,
        },
        {
            title: '8. Ecosystem-level portfolios',
            content: `Learning~Adaptive can construct AI-native ecosystems of companies:
<ul>
  <li>In private markets, portfolio companies are interconnected to unlock operational and strategic synergies.</li>
  <li>In public markets, especially in small caps, boards and executives can be actively trained—often in collaboration with SystematicMe—to improve innovation-driven decision-making.</li>
</ul>
Capital, technology, and governance interact.`,
        },
        {
            title: '9. Model aggregation at scale',
            content: `Beyond advanced, competed strategies, Learning~Adaptive can also exploit a large space of low-risk, low-return patterns by being able to manage models efficiently.
Just as high-frequency trading compounds small edges through volume, Learning~Adaptive compounds many modest, robust models—a greenfield made accessible only through extreme operational efficiency.`,
        },
        {
            title: '10. Open collaboration and revenue sharing',
            content: `The vehicle can collaborate with:
<ul>
  <li>external managers,</li>
  <li>research groups,</li>
  <li>industry partners,</li>
</ul>
sharing revenues where appropriate.
This flexibility is a direct consequence of its architecture-first design.`,
        },
        {
            title: '11. Strategic flow from algorithmic treasuries',
            content: `As companies adopt Algorithmization through SciTheWorld, algorithmic treasury flows naturally emerge from a number of industries—creating aligned, high-quality investment opportunities for Learning~Adaptive.`,
        },
        {
            title: '12. ... And many more',
            content: `Arising from participation in a Group structured to act as a long-term opportunity-generating asset.`,
        },
    ],

    /* ── Awards ── */
    awards: {
        title: "We're Just Doing Our Job...",
        subtitle: '*BUT SOMETIMES WE GET AWARDS FOR                IT',
        items: [
            { name: 'Banking Tech Awards: Best Tech Leader', category: 'Finalist', project: 'Our forward-looking vision', year: '2025' },
            { name: 'Finovate: Innovator of the Year', category: 'Finalist', project: 'Our pioneer work on Agentic AI', year: '2025' },
            { name: 'Bankig Tech Awards: Best Tech of the Future: AI and Data', category: 'Winner', project: 'Our Fractal Platform', year: '2024' },
            { name: 'CogX: Best Innovation in Simulation', category: 'Winner', project: 'Core of our Virtual Reality Simulation', year: '2020' },
            { name: 'Banking Tech Awards: Best Trading Platform', category: 'Winner', project: 'Sergio`s UCL PhD Thesis at BBVA', year: '2017' }
        ],
    },

    /* ── Footer ── */
    footer: {
        isoText: 'Members of both groups: AI and Web3 & Metaverse',
        copyright: 'SciTheWorld. All rights reserved.',
    },

    /* ── Contact Us ── */
    contactUs: {
        title: 'CONTACT US',
    },

    /* ── Cookie Banner ── */
    cookieBanner: {
        title: 'Cookie settings',
        text: 'Our website uses cookies to distinguish you from other users. This helps us to provide you with a more personalized experience when you browse our site and also allows us to improve it. You can choose not to allow some types of cookies.',
        customizeBtn: 'Customize cookies',
        rejectBtn: 'Reject all',
        acceptBtn: 'Accept all',
        saveBtn: 'Save preferences',
        categories: {
            necessary: { name: 'Necessary', description: 'Enable basic security and functionality.', label: 'Required' },
            analytics: { name: 'Analytics', description: 'Allow site performance tracking.' },
            marketing: { name: 'Marketing', description: 'Enable ad personalization and tracking.' }
        },
        on: 'On',
        off: 'Off'
    },

    /* ── Modal ── */
    modal: {
        copyPromptLabel: 'First, copy the prompt:',
        copyButton: 'Copy prompt',
        copiedButton: 'Copied!',
        llmLabel: 'Then, check on the different LLMs:',
    },
};
